services:
  - type: web
    name: medical-shop-biller
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: PORT
        value: 5000